
name: acadify
description: A secure, structured platform for university academic communications and operations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  firebase_messaging: ^14.6.7
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  file_picker: ^5.5.0
  path_provider: ^2.1.1
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.14
  flutter_local_notifications: ^15.1.1
  http: ^1.1.0
  flutter_markdown: ^0.6.17
  image_picker: ^1.0.4
  uuid: ^3.0.7
  timeago: ^3.5.0
  equatable: ^2.0.5
  connectivity_plus: ^4.0.2
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.1.0
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  flutter_spinkit: ^5.2.0
  flutter_slidable: ^3.0.0
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.6
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#673AB7"
  image: "assets/images/splash_logo.png"
  android: true
  ios: true
